// Generated by gencpp from file auto_flight/auto_flight_octomap_state.msg
// DO NOT EDIT!


#ifndef AUTO_FLIGHT_MESSAGE_AUTO_FLIGHT_OCTOMAP_STATE_H
#define AUTO_FLIGHT_MESSAGE_AUTO_FLIGHT_OCTOMAP_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace auto_flight
{
template <class ContainerAllocator>
struct auto_flight_octomap_state_
{
  typedef auto_flight_octomap_state_<ContainerAllocator> Type;

  auto_flight_octomap_state_()
    : header()
    , current_octomap_size(0.0)
    , building_octomap_size(0.0)
    , current_octomap_exist_time(0.0)  {
    }
  auto_flight_octomap_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_octomap_size(0.0)
    , building_octomap_size(0.0)
    , current_octomap_exist_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _current_octomap_size_type;
  _current_octomap_size_type current_octomap_size;

   typedef double _building_octomap_size_type;
  _building_octomap_size_type building_octomap_size;

   typedef double _current_octomap_exist_time_type;
  _current_octomap_exist_time_type current_octomap_exist_time;





  typedef boost::shared_ptr< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> const> ConstPtr;

}; // struct auto_flight_octomap_state_

typedef ::auto_flight::auto_flight_octomap_state_<std::allocator<void> > auto_flight_octomap_state;

typedef boost::shared_ptr< ::auto_flight::auto_flight_octomap_state > auto_flight_octomap_statePtr;
typedef boost::shared_ptr< ::auto_flight::auto_flight_octomap_state const> auto_flight_octomap_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_flight

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'auto_flight': ['/home/wuqi/code/ros/auto_flight_ros/src/auto_flight/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad2b721f0d4d642bd991f6e716fe1247";
  }

  static const char* value(const ::auto_flight::auto_flight_octomap_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad2b721f0d4d642bULL;
  static const uint64_t static_value2 = 0xd991f6e716fe1247ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_flight/auto_flight_octomap_state";
  }

  static const char* value(const ::auto_flight::auto_flight_octomap_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#auto_flight_octomap\n\
\n\
std_msgs/Header header\n\
float64 current_octomap_size\n\
float64 building_octomap_size\n\
float64 current_octomap_exist_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::auto_flight::auto_flight_octomap_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_octomap_size);
      stream.next(m.building_octomap_size);
      stream.next(m.current_octomap_exist_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct auto_flight_octomap_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_flight::auto_flight_octomap_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_flight::auto_flight_octomap_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_octomap_size: ";
    Printer<double>::stream(s, indent + "  ", v.current_octomap_size);
    s << indent << "building_octomap_size: ";
    Printer<double>::stream(s, indent + "  ", v.building_octomap_size);
    s << indent << "current_octomap_exist_time: ";
    Printer<double>::stream(s, indent + "  ", v.current_octomap_exist_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_FLIGHT_MESSAGE_AUTO_FLIGHT_OCTOMAP_STATE_H
